name: tf1-pinn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      # --- Core scientific stack ---
      - tensorflow==1.15.0
      - numpy==1.18.5
      - scipy==1.4.1
      - matplotlib==3.3.4
      - pyDOE==0.3.8

      # --- Compatibility pins (critical for TF1) ---
      - protobuf==3.20.3
      - h5py==2.10.0
      - tensorflow-estimator==1.15.1
      - gast==0.2.2
      - keras-preprocessing==1.1.2
      - keras-applications==1.0.8
      - tensorboard==1.15.0

      # --- Utility & plotting ---
      - ipykernel
      - tqdm
      - pandas
